[package]
name = "embedding-model"
version = "0.1.0"
edition = "2021"

[dependencies]
llama-cpp = { workspace = true }
anyhow = {workspace = true}
clap = { version = "4.5.28", features = ["derive"] }
tracing = "0.1.41"
serde = {workspace = true}
serde_json = {workspace = true}
embedding-common = { path = "../embedding-common" }
config = { version = "0.15.7", features = ["toml", "async"], default-features = false }
zmq = {workspace = true}
uuid = {workspace = true}
rand = "0.9.0"

[features]
default = []
cuda = [ "llama-cpp/cuda"]
metal = ["llama-cpp/metal"]

[[bin]]
name = "model_cli"
path = "src/embedding_cli.rs"

[[bin]]
name = "model_broker"
path = "src/embedding_broker.rs"

[[bin]]
name = "model_worker"
path = "src/embedding_worker.rs"

[[bin]]
name = "model_client"
path = "src/embedding_client.rs"
