[package]
name = "embedding-database"
version = "0.1.0"
edition = "2021"

[dependencies]
#rocksdb = {  version = "0.22.0", features = ["multi-threaded-cf"] }
rocksdb = "0.22.0"
byteorder = "1.5.0"
tokio = {workspace = true}
futures = {workspace = true}
tracing = {workspace = true}
anyhow = { workspace = true }
indexmap = { workspace = true }
num_cpus = { workspace = true }
uuid = { workspace = true }
embedding-common = { path = "../embedding-common" }

[dev-dependencies]
fake = "3.0.1"
tempdir = "0.3.7"
tokio = { version = "1.41.0", features = ["test-util"] }
uuid = {workspace = true}
