[package]
name = "embedding-index"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
uuid = { workspace = true }
tokio = {workspace = true}
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
futures = { workspace = true }
indexmap = { workspace = true }
ndarray = "0.16.1"
rand = "0.8.5"
rayon = "1.10.0"
embedding-common = { path = "../embedding-common" }
embedding-database = { path = "../embedding-database" }

[target.'cfg(not(target_os = "macos"))'.dependencies]
usearch = { version = "2.16.6", features = ["simsimd", "fp16lib", "openmp"] }

[target.'cfg(target_os = "macos")'.dependencies]
usearch = { version = "2.16.7", default-features = false, features = ["fp16lib"] }

[dev-dependencies]
tempdir = "0.3.7"
tokio = { version = "1.41.1", features = ["test-util"] }
simsimd = "6.2.1"
half = "=2.4.1"
