[package]
name = "embedding-processing"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }

ahash = {workspace = true}
chrono = "0.4.38"
zmq = {workspace = true}
async-channel = {workspace = true}


fast-text-splitter = { git = "https://gitlab.com/qimiaio/qimia-ai-dev/fast-text-splitter.git", branch = "feat/merge_level_async" }
lexrank-ndarray = { git = "https://gitlab.com/qimiaio/qimia-ai-dev/lexrank-ndarray.git", branch = "main" }
rayon = "1.10.0"

embedding-common = { path = "../embedding-common" }
embedding-model = { path = "../embedding-model" }
rand = "0.9.0"

[dev-dependencies]
rstest = "0.24.0"
criterion = { version = "0.5.1", features = ["async_tokio"] }
tokio = { version = "1.41.0", features = ["test-util"] }

[[bench]]
name = "benchmarks"
harness = false

[features]
default = []
cuda = [ "embedding-model/cuda"]
metal = ["embedding-model/metal"]
accelerate = ["lexrank-ndarray/accelerate"]
blas = ["lexrank-ndarray/blas"]
mkl = ["lexrank-ndarray/mkl"]