[package]
name = "embedding-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = {workspace = true}
tokio = { workspace = true}
futures = {workspace = true}
tracing = {workspace = true}
tracing-subscriber = {workspace = true}
clap = { version = "4.5.20", features = ["derive"] }


embedding-common = { path = "../embedding-common" }
embedding-processing = { path = "../embedding-processing" }
embedding-database = { path = "../embedding-database" }