

[model]
#gguf_file = "models/bge-reranker-v2-m3-q4_k_m.gguf"
gguf_file = "models/bge-reranker-v2-m3-f16.gguf"
#cpu = false
ngl = 1000
max_tokens = 2048
verbose = false


[zmq]
host = "127.0.0.1"
frontend_port = 5557
backend_port = 5570
num_workers = 1
