[package]
name = "reranking-model"
version = "0.1.0"
edition = "2021"

[dependencies]
llama-cpp = { workspace = true }
anyhow = "1.0.95"
clap = { version = "4.5.28", features = ["derive"] }
tracing = "0.1.41"
serde = {workspace = true}
embedding-common = { path = "../embedding-common" }
zmq = {workspace = true}
uuid = {workspace = true}
rmp-serde = { workspace = true }
serde_json = {workspace = true}



[features]
default = []
cuda = [ "llama-cpp/cuda"]
metal = ["llama-cpp/metal"]

[[bin]]
name = "reranking_cli"
path = "src/model_cli.rs"

[[bin]]
name = "reranking_broker"
path = "src/model_broker.rs"

[[bin]]
name = "reranking_worker"
path = "src/model_worker.rs"

[[bin]]
name = "reranking_client"
path = "src/model_client.rs"
