[package]
name = "embedding-server"
version = "0.1.0"
edition = "2021"

[dependencies]
zeromq = "0.4.1"
async-channel = "2.3.1"
anyhow = { workspace = true }
futures = { workspace = true }
clap = { workspace = true }
tracing = { workspace = true}
num_cpus = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
serde = { workspace = true }
serde_repr = { workspace = true }
chrono = { workspace = true }
indexmap = { workspace = true }

embedding-common = { path = "../embedding-common" }
embedding-database = { path = "../embedding-database" }
embedding-index = { path = "../embedding-index" }
embedding-processing = { path = "../embedding-processing" }